character: L36_230_61
use_multichar: True
save_root: /project/qiuf/expr-capture
emb_backbone: mae_emb
faceware_ratio: 0.0
batch_size: 128
lr: 0.00001
lr_D: 0.000001
patience: 30
save_step: 10
# loss weight
weight_rig: 10
weight_img: 1
weight_mouth: 10
weight_emb: 100
weight_D: 0.01
weight_symm: 1
id_embedding_dim: 16
pretrained: '' 
mode: 'train'
train_step_per_epoch: 500
eval_step_per_epoch: 100
seed: 101010